# Generated by Django 3.1 on 2020-08-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('further_maths', '0003_remove_proof_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='title',
            field=models.CharField(default='Add title here', max_length=100),
        ),
    ]
